name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "📦 install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "🔍 run tests"
        run: npm t

  lint:
    name: Code standards
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2

      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16


      - name: "📦 install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "🔍 lint code"
        run: npm run lint
